### ISSUE TITLE
GraphQL deploy fails with goth-vimeo-input installed

### ISSUE THREAD

**Issue by scowley101** [bradley/sanity-plugin-vimeo-input#1]
Hi Bradley,

I'm fairly new to this, so apologies if I am making some basic error here.

I am building a project with Gatsby, using Sanity for the backend. I installed your plugin, which seems to work great on the Sanity end but when I try and redeploy my GraphQL to get the vimeo data through to the API, I am getting the following error:

`TypeError: generateSchema is not a function
    at ~/pah-1/sanity/node_modules/@sanity/core/lib/actions/graphql/deployApiAction.js:99:16
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (~/Documents/Coding/gatsby-projects/phoebe-anne-harris/sanity/node_modules/@sanity/core/lib/actions/graphql/deployApiAction.js:3:103)
    at _next (~/Documents/Coding/gatsby-projects/phoebe-anne-harris/sanity/node_modules/@sanity/core/lib/actions/graphql/deployApiAction.js:5:194)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)`

I have reverted back and redeployed without your plugin and it deploys as expected.

Would love some help sorting this as your plugin is great otherwise. Let me know if you need any other info about my setup.

Sam

**Comment by bradley** [comment]
@scowley101 hmm Im not seeing anything there that immediately jumps out as an issue with the plugin, not to say it doesn't. Did you sort out this issue in the interim between posting and now? Wondering if maybe you may try _just_ adding the plugin, doing nothing else, and seeing if the issue persists. To be honest Ive been a little out of Sanity since posting this (while intending to use it in the future still), so may be missing something obvious in that error.

**Comment by scowley101** [comment]
@bradley Thaks for coming back to me.

Still having the same issue but I suspect it is user error on my part. The issue seems to be around the versions of React and Reactdom I have insalled in the project.

`✝  gatsby-projects/phoebe-anne-harris/sanity   master±  sanity install goth-vimeo-input 

✔ Saved lockfile

✔ Saved lockfile
Plugin 'sanity-plugin-goth-vimeo-input' installed
 ✝  gatsby-projects/phoebe-anne-harris/sanity   master±  npm start

> phoebeanneharrisbackend@1.0.0 start
> sanity start


[ERROR] The following package versions are no longer supported and needs to be upgraded:

  react (installed: 17.0.1, want: ^16.9)
  react-dom (installed: 17.0.1, want: ^16.9)

  To upgrade run either:

  yarn add "react@^16.9" "react-dom@^16.9"

  or

  npm install "react@^16.9" "react-dom@^16.9"

Read more at https://docs.sanity.io/help/upgrade-packages

npm ERR! code 1
npm ERR! path /Users/Hoops/Documents/Coding/gatsby-projects/phoebe-anne-harris/sanity
npm ERR! command failed
npm ERR! command sh -c sanity start

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Hoops/.npm/_logs/2021-03-09T08_23_03_735Z-debug.log
 ✘ ✝  gatsby-projects/phoebe-anne-harris/sanity   master±  `

When i try changing the version as suggested i get:

`✘ ✝  gatsby-projects/phoebe-anne-harris/sanity   master±  npm install "react@^16.9" "react-dom@^16.9"
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: react@16.14.0
npm ERR! node_modules/react
npm ERR!   react@"^16.9" from the root project
npm ERR!   peer react@">= 15.3" from boundless-arrow-key-navigation@1.1.0
npm ERR!   node_modules/boundless-arrow-key-navigation
npm ERR!     boundless-arrow-key-navigation@"^1.1.0" from @sanity/components@1.150.7
npm ERR!     node_modules/@sanity/components
npm ERR!       @sanity/components@"1.150.7" from @sanity/base@1.150.7
npm ERR!       node_modules/@sanity/base
npm ERR!         @sanity/base@"1.150.7" from @sanity/components@1.150.7
npm ERR!         5 more (@sanity/default-layout, @sanity/desk-tool, ...)
npm ERR!       4 more (@sanity/default-layout, @sanity/desk-tool, ...)
npm ERR!     boundless-arrow-key-navigation@"^1.1.0" from @sanity/desk-tool@1.150.7
npm ERR!     node_modules/@sanity/desk-tool
npm ERR!       @sanity/desk-tool@"1.150.7" from the root project
npm ERR!   47 more (create-react-context, flux, react-animate-height, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.0.0" from react-json-inspector@7.1.1
npm ERR! node_modules/react-json-inspector
npm ERR!   react-json-inspector@"^7.1.1" from @sanity/desk-tool@1.150.7
npm ERR!   node_modules/@sanity/desk-tool
npm ERR!     @sanity/desk-tool@"1.150.7" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/Hoops/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Hoops/.npm/_logs/2021-03-09T08_24_16_676Z-debug.log
 ✘ ✝  gatsby-projects/phoebe-anne-harris/sanity   master±  `

If I then install with --legacy-peer-deps, sanity will compile fine, but I get the error in the last message when trying to redeploy Graphql.

As I say this feel like it could be more to do with me screwing up in npm rather than the plugin itself. But if you have any suggestions I would appreciate it.

**Comment by scowley101** [comment]
@bradley Thaks for coming back to me.

Still having the same issue but I suspect it is user error on my part. The issue seems to be around the versions of React and Reactdom I have insalled in the project.

```
✝  gatsby-projects/phoebe-anne-harris/sanity   master±  sanity install goth-vimeo-input

✔ Saved lockfile

✔ Saved lockfile
Plugin 'sanity-plugin-goth-vimeo-input' installed
✝  gatsby-projects/phoebe-anne-harris/sanity   master±  npm start

    phoebeanneharrisbackend@1.0.0 start
    sanity start

[ERROR] The following package versions are no longer supported and needs to be upgraded:

react (installed: 17.0.1, want: ^16.9)
react-dom (installed: 17.0.1, want: ^16.9)

To upgrade run either:

yarn add "react@^16.9" "react-dom@^16.9"

or

npm install "react@^16.9" "react-dom@^16.9"

Read more at https://docs.sanity.io/help/upgrade-packages

npm ERR! code 1
npm ERR! path /Users/Hoops/Documents/Coding/gatsby-projects/phoebe-anne-harris/sanity
npm ERR! command failed
npm ERR! command sh -c sanity start

npm ERR! A complete log of this run can be found in:
npm ERR! /Users/Hoops/.npm/_logs/2021-03-09T08_23_03_735Z-debug.log
✘ ✝  gatsby-projects/phoebe-anne-harris/sanity   master±  
```

When i try changing the version as suggested i get:

```
✘ ✝  gatsby-projects/phoebe-anne-harris/sanity   master±  npm install "react@^16.9" "react-dom@^16.9"
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: react@16.14.0
npm ERR! node_modules/react
npm ERR! react@"^16.9" from the root project
npm ERR! peer react@">= 15.3" from boundless-arrow-key-navigation@1.1.0
npm ERR! node_modules/boundless-arrow-key-navigation
npm ERR! boundless-arrow-key-navigation@"^1.1.0" from @sanity/components@1.150.7
npm ERR! node_modules/@sanity/components
npm ERR! @sanity/components@"1.150.7" from @sanity/base@1.150.7
npm ERR! node_modules/@sanity/base
npm ERR! @sanity/base@"1.150.7" from @sanity/components@1.150.7
npm ERR! 5 more (@sanity/default-layout, @sanity/desk-tool, ...)
npm ERR! 4 more (@sanity/default-layout, @sanity/desk-tool, ...)
npm ERR! boundless-arrow-key-navigation@"^1.1.0" from @sanity/desk-tool@1.150.7
npm ERR! node_modules/@sanity/desk-tool
npm ERR! @sanity/desk-tool@"1.150.7" from the root project
npm ERR! 47 more (create-react-context, flux, react-animate-height, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.0.0" from react-json-inspector@7.1.1
npm ERR! node_modules/react-json-inspector
npm ERR! react-json-inspector@"^7.1.1" from @sanity/desk-tool@1.150.7
npm ERR! node_modules/@sanity/desk-tool
npm ERR! @sanity/desk-tool@"1.150.7" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/Hoops/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR! /Users/Hoops/.npm/_logs/2021-03-09T08_24_16_676Z-debug.log
✘ ✝  gatsby-projects/phoebe-anne-harris/sanity   master±  
```

If I then install with --legacy-peer-deps, sanity will compile fine, but I get the error in the last message when trying to redeploy Graphql.

As I say this feel like it could be more to do with me screwing up in npm rather than the plugin itself. But if you have any suggestions I would appreciate it.

**Comment by bradley** [comment]
Closing this as it doesnt appear related to the plugin. Let me know if you find otherwise.
